sanpietroinlamosa/urls.py
#from django.conf.urls import url
from django.conf.urls import include, url, patterns
from django.contrib import admin
from sito import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^pagina/(?P<post_id>\d+)/$', views.PageDetailView, name='pagina'),
    url(r'^categoria/(?P<post_id>\d+)/$', views.CategoriaView, name='categoria'),
    url(r'^attivita/(?P<post_id>\d+)/$', views.AttivitaView, name='attivita'),
    url(r'^collana/$', views.CollanaView, name='collana'),
    url(r'^luoghi/$', views.LuoghiView, name='luoghi'),
    url(r'^luoghi/(?P<post_id>\d+)/$', views.LuoghiDetailView, name='luogo'),
    url(r'^monastero/$', views.MonasteroView, name='monastero'),
    url(r'^monastero/(?P<post_id>\d+)/$', views.MonasteroDetailView, name='sale'),
    url(r'^contatti/$', views.ContattiView, name='contatto'),
    url(r'^partner/$', views.PartnerView, name='partner'),
    url(r'^galleria/$', views.GalleriaView, name='galleria'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^success/$', views.success, name='success'),
    url(r'^cluniacensi/$', views.CluniacensiView, name='cluniacensi'),
    url(r'^news/$', views.NewsView, name='news'),
    url(r'^news/(?P<post_id>\d+)/$', views.NewsDetailView, name='news-dettaglio'),
    ##api
    url(r'^api/cluniacensi/$', views.cluniacensiJson, name='cluniacensiJson'), ##json
    ##tinymce
    url(r'^tinymce/', include('tinymce.urls')),


]

if settings.DEBUG:  
        urlpatterns += patterns('',  
                                #REMOVE IT in production phase  
                                (r'^media/(?P<path>.*)$', 'django.views.static.serve',  
                                {'document_root': settings.MEDIA_ROOT})
          )

sito/models.py
from __future__ import unicode_literals

from django.db import models
from image_cropping import ImageRatioField, ImageCropField

from datetime import datetime, timedelta, time, date
from django.utils.timesince import timesince

from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField
from filer.fields.folder import FilerFolderField

from tinymce.models import HTMLField

from django.utils import timezone

from django import forms



# Create your models here.

class Categorie(models.Model):
    titolo = models.CharField(max_length=100)
    sottotitolo = models.CharField(max_length=250, null=True, blank=True)

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Attivita Categorie"



class Immagini(models.Model):
    titolo = models.CharField(max_length=100, verbose_name="Titolo:")
    image = models.ImageField(blank=True, null=True, upload_to='uploaded_images')
    didascalia = models.TextField(null=True, blank=True)
    cropping = ImageRatioField('image', '500x480')
    slider = ImageRatioField('image', '1920x1280')
    revolution = ImageRatioField('image', '1170x500', verbose_name="Revolution Gallery")
    thumb = ImageRatioField('image', '595x335', verbose_name="Miniatura")
    croplibero = ImageRatioField('image', '595x335', free_crop=True, verbose_name="Ritaglio Libero")
    croppinguno = ImageRatioField('image', '1140x487', free_crop=True)
    croppingdue = ImageRatioField('image', '198x132')
    croppingtre = ImageRatioField('image', '1199x674')
    pub_date = models.DateTimeField('date published')

    def image_img(self):
        if self.image:
            return u'<img src="%s" style="width:200px"/>' % self.image.url
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Thumb'
    image_img.allow_tags = True

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Galleria Immagini"
        ordering = ['id']



CSS_SLIDER = (
    ('0', 'stile uno'),
    ('1', 'stile due'),
                )
class Slider(models.Model):
    titolo = models.CharField(max_length=100, verbose_name="Titolo del Progetto:")
    image = models.ImageField(blank=True, null=True, upload_to='slider')
    scritta = models.TextField(null=True, blank=True)
    didascalia = models.TextField(null=True, blank=True)
    link = models.TextField(null=True, blank=True)
    cropping = ImageRatioField('image', '500x480')
    slider = ImageRatioField('image', '1920x1280')
    revolution = ImageRatioField('image', '1170x500', verbose_name="Revolution Gallery")
    thumb = ImageRatioField('image', '595x335', verbose_name="Miniatura")
    croplibero = ImageRatioField('image', '595x335', free_crop=True, verbose_name="Ritaglio Libero")
    croppinguno = ImageRatioField('image', '1140x487', free_crop=True)
    croppingdue = ImageRatioField('image', '198x132')
    croppingtre = ImageRatioField('image', '1199x674')
    pub_date = models.DateTimeField('date published')
    impaginazione = models.CharField(choices=CSS_SLIDER, max_length=200, null=True, blank=True)
    active = models.BooleanField('attiva',
                                    default=False)

    def image_img(self):
        if self.image:
            return u'<img src="%s" style="width:300px"/>' % self.image.url
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Thumb'
    image_img.allow_tags = True

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Slider"
        ordering = ['id']



class Documenti(models.Model):
    titolo = models.CharField(max_length=100, verbose_name="Titolo")
    image = models.FileField(blank=True, null=True, upload_to='documenti')
    allegato = models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')
    didascalia = models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Documenti"
        ordering = ['id']



class Video(models.Model):
    titolo = models.CharField("Titolo del Video:", max_length=100, null=True, blank=True)
    codice = models.CharField("Codice ID YouTube:", max_length=100, null=True, blank=True)
    youtubeurl = models.CharField("Indirizzo url youtube:", max_length=100, null=True, blank=True)
    start = models.IntegerField(default=0, null=True, blank=True, verbose_name="Punto di Partenza del Filmato in secondi")
    embedded = models.TextField("Codice Embedded YouTube", null=True, blank=True)
    thumb = models.ImageField(upload_to='uploaded_thumb_youtube', null=True, blank=True)
    link = models.CharField(max_length=100, null=True, blank=True)
    didascalia = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Galleria Video"



class Attivita(models.Model):
    titolo = models.CharField("Titolo:", max_length=100, null=True, blank=True)
    titolomenu = models.CharField("Titolo Menu:", max_length=100, null=True, blank=True)
    revhome = models.BooleanField('Home Gallery',
                                    default=False,
                                    help_text="Mostra IMG nella slide in home")
    categoria = models.ManyToManyField(Categorie, null=True, blank=True)
    #inizio = models.DateField(null=True, blank=True, verbose_name="Inizio Evento")
    #fine = models.DateField( null=True, blank=True, verbose_name="Fine Evento")
    inizio = models.DateTimeField(null=True, blank=True, verbose_name="Inizio Evento")
    fine = models.DateTimeField( null=True, blank=True, verbose_name="Fine Evento")
    luogo = models.CharField(max_length=200,  null=True, blank=True,
    						verbose_name="Luogo dell'evento",
    						help_text="Esempio: San Pietro in Lamosa - sala 5")
    latitudine = models.CharField(max_length=200, null=True, blank=True, help_text="Non necessario")
    longitudine = models.CharField(max_length=200, null=True, blank=True, help_text="Non necessario")
    tel = models.CharField(max_length=200,  null=True, blank=True)
    web = models.CharField(max_length=200,  null=True, blank=True)
    email = models.CharField(max_length=200,  null=True, blank=True)
    introduzione = models.TextField(null=True, blank=True, verbose_name="Descrizione Breve per introduzione")
    #body = models.TextField(null=True, blank=True, verbose_name="Descrizione")
    body = HTMLField(null=True, blank=True, verbose_name="Descrizione")
    locandina = models.ImageField(blank=True, null=True, upload_to='attivita_locandine')
    image = models.ImageField(blank=True, null=True, upload_to='attivita')
    thumb = ImageRatioField('image', '600x600')
    cropping = ImageRatioField('image', '1200x1200')
    slider = ImageRatioField('image', '1920x1280')
    revolution = ImageRatioField('image', '1170x500')
    croplibero = ImageRatioField('image', '595x335', free_crop=True, verbose_name="Ritaglio Libero")
    album = FilerFolderField(null=True, blank=True)
    video = models.ManyToManyField(Video, null=True, blank=True)
    galleria = models.ManyToManyField(Immagini, null=True, blank=True, verbose_name="Seleziona Immagini Galleria")
    documenti = models.ManyToManyField(Documenti, null=True, blank=True, verbose_name="Documenti - Allegati")
    pub_date = models.DateTimeField('date published')

    def image_img(self):
        if self.image:
            return u'<img src="%s" style="width:200px"/>' % self.image.url
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Thumb'
    image_img.allow_tags = True

    def cate(self):
    	a = "\n"
    	ca = self.categoria.all()
    	for c in ca:
    		a += c.titolo + "\n"
    	return a

    def delta(self):
        now = date.today()
        differenza = now - self.fine
        ok = differenza
        return ok

    def attesa(self):
        now = date.today()
        differenza = self.inizio - now
        ok = differenza
        return ok

    ## filtro x data
    #@property
    def is_past_due(self):
        if self.inizio > datetime.now():
            return True
        return False

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Attivita"
        ordering = ['-inizio']



class Page(models.Model):
    titolo = models.CharField("Titolo:", max_length=100, null=True, blank=True)
    titolomenu = models.CharField("Titolo Menu:", max_length=100, null=True, blank=True)
    revhome = models.BooleanField('Home Gallery',
                                    default=False,
                                    help_text="Mostra IMG nella slide in home")
    introduzione = models.TextField(null=True, blank=True, verbose_name="Descrizione Breve per introduzione")
    body = models.TextField(null=True, blank=True, verbose_name="Descrizione")
    image = models.ImageField(blank=True, null=True, upload_to='pagine')
    thumb = ImageRatioField('image', '600x600')
    cropping = ImageRatioField('image', '1200x1200')
    slider = ImageRatioField('image', '1920x1280')
    revolution = ImageRatioField('image', '1170x500')
    croplibero = ImageRatioField('image', '595x335', free_crop=True, verbose_name="Ritaglio Libero")
    album = FilerFolderField(null=True, blank=True)
    video = models.ManyToManyField(Video, null=True, blank=True)
    galleria = models.ManyToManyField(Immagini, null=True, blank=True, verbose_name="Seleziona Immagini Galleria")
    documenti = models.ManyToManyField(Documenti, null=True, blank=True, verbose_name="Documenti - Allegati")
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.titolo

    class Meta:
        verbose_name_plural = "Pagine"



class Collana(models.Model):
    titolo = models.CharField(max_length=100)

sito/views.py
from django.shortcuts import render

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import ListView, DetailView
from django.template.loader import render_to_string
from sito.models import *
from django.core.mail import send_mail
from filer.models import *

from datetime import datetime

from django.core import serializers





# Create your views here.
def HomePage(request):
    att_list = Attivita.objects.filter(revhome=True).order_by('-id')
    slider_list = Slider.objects.filter(active=True)
    context = {'slider_list':slider_list,
                'att_list':att_list}
    return render_to_response('index.html', context, context_instance=RequestContext(request))


def PageDetailView(request, post_id):
    page = Page.objects.get(pk=post_id)
    context = {'page': page}
    return render_to_response('pagina.html', context, context_instance=RequestContext(request))


def CategoriaView(request, post_id):
    categoria = Categorie.objects.get(pk=post_id)
    mytime = datetime.now()
    context = {'categoria': categoria,
                'mytime': mytime
                }
    return render_to_response('categorie.html', context, context_instance=RequestContext(request))


def AttivitaView(request, post_id):
    attivita = Attivita.objects.get(pk=post_id)
    filer_list = Image.objects.filter(folder_id = attivita.album)
    context = {'attivita': attivita,
                'filer_list': filer_list}
    return render_to_response('attivita.html', context, context_instance=RequestContext(request))


def CollanaView(request):
    collana_list = Collana.objects.all().order_by('id')
    context = {'collana_list': collana_list}
    return render_to_response('collana.html', context, context_instance=RequestContext(request))


def LuoghiView(request):
    luoghi = Luoghi.objects.all()
    context = {'luoghi': luoghi}
    return render_to_response('luoghi.html', context, context_instance=RequestContext(request))


def LuoghiDetailView(request, post_id):
    luogo = Luoghi.objects.get(pk=post_id)
    filer_list = Image.objects.filter(folder_id = luogo.album)
    context = {'luogo': luogo,
                'filer_list': filer_list}
    return render_to_response('luogo.html', context, context_instance=RequestContext(request))


def MonasteroView(request):
    monastero_list = Monastero.objects.all()
    context = {'monastero_list': monastero_list}
    return render_to_response('monastero.html', context, context_instance=RequestContext(request))


def MonasteroDetailView(request, post_id):
    monastero = Monastero.objects.get(pk=post_id)
    filer_list = Image.objects.filter(folder_id = monastero.album)
    context = {'monastero': monastero,
                'filer_list': filer_list}
    return render_to_response('stanze.html', context, context_instance=RequestContext(request))


def ContattiView(request):
    return render_to_response('contatti.html', context_instance=RequestContext(request))


def PartnerView(request):
    partner_list = Partner.objects.all()
    context = {'partner_list': partner_list}
    return render_to_response('partner.html', context, context_instance=RequestContext(request))


def GalleriaView(request):
    filer_list = Image.objects.all
    context = {'filer_list': filer_list}
    return render_to_response('galleria.html', context, context_instance=RequestContext(request))


def CluniacensiView(request):
    cluniacensi_list = Cluniacensi.objects.all()
    context = {'cluniacensi_list': cluniacensi_list}
    return render_to_response('cluniacensi.html', context, context_instance=RequestContext(request))

def NewsView(request):
    news_list = News.objects.all().order_by('-pub_date')
    context = {'news_list': news_list}
    return render_to_response('news.html', context, context_instance=RequestContext(request))


def NewsDetailView(request, post_id):
    news = News.objects.get(pk=post_id)
    filer_list = Image.objects.filter(folder_id = news.album)
    context = {'news': news,
                'filer_list': filer_list}
    return render_to_response('news_dettaglio.html', context, context_instance=RequestContext(request))



def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            subject = 'Iscrizione Newsletter sanpietroinlamosa'
            #message = form.cleaned_data['messaggio']
            message = render_to_string('contact.txt', {'post': request.POST})
            sender = form.cleaned_data['email']
            cc_myself = False

            recipients = ['pierangelo1982@gmail.com']
            if cc_myself:
                recipients.append(sender)
        
            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/success/') # Redirect after POST
    else:
        form = ContactForm() # An unbound form

    #return render_to_response('contact.html', {'form': form,})
    return render_to_response('contact.html', context_instance=RequestContext(request))


def success(request):
    return render_to_response('success.html', context_instance=RequestContext(request))


#### JSON
def cluniacensiJson(request):
    data = serializers.serialize("json", Cluniacensi.objects.all())
    return HttpResponse(data, content_type='application/json;')  

    

sito/templates/attivita.html
{% extends 'base.html' %}
{% block content %}
<style>	
	.fh5co-nav-toggle i::before, 
	.fh5co-nav-toggle i::after {
	    content: '';
	    width: 25px;
	    height: 3px;
	    background: #000;
	    position: absolute;
	    left: 0;
	    -webkit-transition: 0.2s;
	    -o-transition: 0.2s;
	    transition: 0.2s;
	}
	
	.fh5co-nav-toggle > span {
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    position: absolute;
    left: 0;
    top: 0;
    z-index: 99;
    width: 100px;
    margin-top: 12px;
    color: #000;
    margin-left: -70px;
    font-family: "Montserrat", arial, sans-serif;
    letter-spacing: 2px;
    font-size: 15px;
    text-transform: uppercase;
}

.fh5co-nav-toggle i::before {
  top: -7px;
}
.fh5co-nav-toggle i::after {
  bottom: -7px;
}
.fh5co-nav-toggle:hover i::before {
  top: -10px;
}
.fh5co-nav-toggle:hover i::after {
  bottom: -10px;
}
.fh5co-nav-toggle.active i {
	background: transparent;
}
.fh5co-nav-toggle.active i::before {
  top:0;
  -webkit-transform: rotateZ(45deg);
     -moz-transform: rotateZ(45deg);
      -ms-transform: rotateZ(45deg);
       -o-transform: rotateZ(45deg);
          transform: rotateZ(45deg);
}
.fh5co-nav-toggle.active i::after {
  bottom:0;
  -webkit-transform: rotateZ(-45deg);
     -moz-transform: rotateZ(-45deg);
      -ms-transform: rotateZ(-45deg);
       -o-transform: rotateZ(-45deg);
          transform: rotateZ(-45deg);
}
.fh5co-nav-toggle {
	float: right;
  position: relative;
  top: 12px;
  right: 0px;
  margin-right: -20px;
  z-index: 21;
  padding: 6px 0 0 0;
  display: block;
  color: #000000;

  height: 44px;
  width: 44px;
  border-bottom: none!important;
  > span {
	@include inline-block;
	position: absolute;
	left: 0;
	top: 0;
	z-index: 99;
	width: 100px;
	margin-top: 12px;
	color: $brand-black;
	margin-left: -70px;
	font-family: $font-monsterrat;
	letter-spacing: 2px;
	font-size: 15px;
	text-transform: uppercase;
	.scrolled & {
		color: $brand-black;
	}
  }
}

.consiglio-titolo {
	background: #fbbb01;
	color: #ffffff;
	text-align:center;
}

#fh5co-features, #fh5co-features-2, #fh5co-features-3, #fh5co-products, #fh5co-faqs {
    position: relative;
    padding: 2em 0;
}

.fh5co-nav-toggle > span {
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    position: absolute;
    left: 0;
    top: 0;
    z-index: 99;
    width: 100px;
    margin-top: 12px;
    color: #000000;
    margin-left: -70px;
    font-family: "Montserrat", arial, sans-serif;
    letter-spacing: 2px;
    font-size: 15px;
    text-transform: uppercase;
}

.fh5co-nav-toggle i {
    position: relative;
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    width: 25px;
    height: 3px;
    color: #fff;
    font: bold 14px/.4 Helvetica;
    text-transform: uppercase;
    text-indent: -55px;
    background: #000000;
    transition: all .2s ease-out;
}


.fh5co-nav-toggle.active i::before, 
.fh5co-nav-toggle.active i::after {
    background: #000;
}
	</style>

	

<div id="fh5co-page">

			
<h1 class="titolo-consiglio" style="background: #fbbb01; color: #4d4d4f; text-align:center; margin: 0px; padding:10px;">
	&nbsp;
</h1>

<div id="fh5co-features" data-section="features">


	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img src="/media/{{attivita.locandina}}" class="img-responsive" style="margin-top:20px;">
         {% for filer in filer_list %}{% load thumbnail %} 
          <img src="{% thumbnail filer.image 600x400 crop %}" class="img-responsive" style="margin-top:20px;">
        {% endfor %}
			</div>

			<div class="col-md-8 fh5co-section-heading text-center">
				<h2 id=""class="fh5co-lead to-animate" style="text-align: left">{{attivita.titolo}}</h2>
				<h4 style="text-align: left">
					{% if attivita.fine %}
						Dal: {{attivita.inizio|date:'d-m-Y'}}  Al: {{attivita.fine|date:'d-m-Y'}}
					{% else %}
						il {{attivita.inizio|date:'d-m-Y'}}
					{% endif %}
				</h4>
				<h4 style="text-align: left">{{attivita.luogo}}</h4>
				<p class="fh5co-sub to-animate" style="text-align:justify;">
					{{attivita.body|safe}}
				</p>
      			{% for doc in attivita.documenti.all %}
        		<p style="text-align: left">
          			<a href="/media/{{doc.allegato}}" target="_Blank"><i class="fa fa-file-pdf-o"></i> {{doc.titolo}}</a>
        		</p>
      			{% endfor %}

			</div>
		</div><!-- row -->
	</div><! -- container -->

</div>

</div>

{% endblock %}

sito/templates/categorie.html
{% extends 'base.html' %}

{% block content %}


<style>
	.fh5co-nav-toggle i::before,
	.fh5co-nav-toggle i::after {
	    content: '';
	    width: 25px;
	    height: 3px;
	    background: #000;
	    position: absolute;
	    left: 0;
	    -webkit-transition: 0.2s;
	    -o-transition: 0.2s;
	    transition: 0.2s;
	}

	.fh5co-nav-toggle > span {
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    position: absolute;
    left: 0;
    top: 0;
    z-index: 99;
    width: 100px;
    margin-top: 12px;
    color: #000;
    margin-left: -70px;
    font-family: "Montserrat", arial, sans-serif;
    letter-spacing: 2px;
    font-size: 15px;
    text-transform: uppercase;
}

.fh5co-nav-toggle i::before {
  top: -7px;
}
.fh5co-nav-toggle i::after {
  bottom: -7px;
}
.fh5co-nav-toggle:hover i::before {
  top: -10px;
}
.fh5co-nav-toggle:hover i::after {
  bottom: -10px;
}
.fh5co-nav-toggle.active i {
	background: transparent;
}
.fh5co-nav-toggle.active i::before {
  top:0;
  -webkit-transform: rotateZ(45deg);
     -moz-transform: rotateZ(45deg);
      -ms-transform: rotateZ(45deg);
       -o-transform: rotateZ(45deg);
          transform: rotateZ(45deg);
}
.fh5co-nav-toggle.active i::after {
  bottom:0;
  -webkit-transform: rotateZ(-45deg);
     -moz-transform: rotateZ(-45deg);
      -ms-transform: rotateZ(-45deg);
       -o-transform: rotateZ(-45deg);
          transform: rotateZ(-45deg);
}
.fh5co-nav-toggle {
	float: right;
  position: relative;
  top: 12px;
  right: 0px;
  margin-right: -20px;
  z-index: 21;
  padding: 6px 0 0 0;
  display: block;
  color: #000000;

  height: 44px;
  width: 44px;
  border-bottom: none!important;
  > span {
	@include inline-block;
	position: absolute;
	left: 0;
	top: 0;
	z-index: 99;
	width: 100px;
	margin-top: 12px;
	color: $brand-black;
	margin-left: -70px;
	font-family: $font-monsterrat;
	letter-spacing: 2px;
	font-size: 15px;
	text-transform: uppercase;
	.scrolled & {
		color: $brand-black;
	}
  }
}

.consiglio-titolo {
	background: #fbbb01;
	color: #ffffff;
	text-align:center;
}

#fh5co-features, #fh5co-features-2, #fh5co-features-3, #fh5co-products, #fh5co-faqs {
    position: relative;
    padding: 2em 0;
}

.fh5co-nav-toggle > span {
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    position: absolute;
    left: 0;
    top: 0;
    z-index: 99;
    width: 100px;
    margin-top: 12px;
    color: #000000;
    margin-left: -70px;
    font-family: "Montserrat", arial, sans-serif;
    letter-spacing: 2px;
    font-size: 15px;
    text-transform: uppercase;
}

.fh5co-nav-toggle i {
    position: relative;
    display: -moz-inline-stack;
    display: inline-block;
    zoom: 1;
    width: 25px;
    height: 3px;
    color: #fff;
    font: bold 14px/.4 Helvetica;
    text-transform: uppercase;
    text-indent: -55px;
    background: #000000;
    transition: all .2s ease-out;
}


.fh5co-nav-toggle.active i::before,
.fh5co-nav-toggle.active i::after {
    background: #000;
}
	</style>


<div id="fh5co-page">
	<h1 class="titolo-consiglio" style="background: #fbbb01; color: #4d4d4f; text-align:center; margin: 0px; padding:10px;">&nbsp;</h1>

<div id="fh5co-features" data-section="features">

	<div class="container">

		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-10 fh5co-section-heading text-center">
			   <h2 id=""class="fh5co-lead to-animate" style="text-align: center">{{categoria.titolo}}</h2>
		  </div>

			<div class="col-md-1"></div>
		</div><!-- row -->

    <div class="row">
      {% for at in categoria.attivita_set.all %}
      <div class="col-md-4 col-sm-6 col-xs-6 col-xs-12">
        <a href="{% url 'attivita' at.id %}" class="fh5co-figure">
          <figure>{% load cropping %}
            <img src="{% cropped_thumbnail at "thumb" %}" alt="Free HTML5 Responsive Template" class="img-responsive">
          </figure>
          <h2 class="">{{at.titolo}}</h2>
          <h4>{{at.inizio|date:'d-m-Y'}}</h4>
          <p class="fh5co-figure-text">{{at.introduzione|safe|truncatechars:140}}</p>
        </a>
      </div>
      {% endfor %}
    </div><!-- row -->




  </div><!-- container -->

</div>

</div>


{% endblock %}

sito/templates/index.html
{% extends 'base.html' %}

{% block content %}

		{% include 'componenti/slider.html' %}

		{% include 'componenti/widget_menu.html' %}

		{% include 'componenti/widget_pagine.html' %}



		<div id="fh5co-pricing" data-section="pricing" style="margin-bottom:0px; margin-top:0px;padding:0px;">
			<div class="container">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11551.44633807495!2d10.02871751048628!3d45.640942732296374!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa69af7f5d261e296!2sMonastero+di+San+Pietro+in+Lamosa!5e0!3m2!1sit!2sit!4v1456394540037" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
				
{% include 'componenti/newsletter.html' %}
</div>



{% endblock %}